version: '3'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /app/node_modules
      - ./:/app
